#/***********************************************************************
#* copyright (c) 2004-2006 MALET Jean-luc aka cityhunter
#* This library is free software; you can redistribute it and/or modify
#* it under the terms of the LGPL v2.1 or latter at your option
#* http://www.gnu.org/copyleft/lesser.html
#************************************************************************/


tags :: clean_tags
	ctags -R ${TOPSRC_DIR}                            
	find -type d -regex "\./[^.]*" ! -regex ".*CVS.*" | xargs -i ln -s ${TOPSRC_DIR}/tags {}/tags

clean : clean_tags

clean_tags :
	find -name "tags" | xargs rm -f

