#/***********************************************************************
#* copyright (c) 2004-2006 MALET Jean-luc aka cityhunter
#* This library is free software; you can redistribute it and/or modify
#* it under the terms of the LGPL v2.1 or latter at your option
#* http://www.gnu.org/copyleft/lesser.html
#************************************************************************/
include $(shell ${confiserie}/C/make_autopcflags.sh ${bin_PROGRAMS} ${sbin_PROGRAMS} ${noinst_PROGRAMS} ${custom_PROGRAMS}



