#/***********************************************************************
#* copyright (c) 2004-2006 MALET Jean-luc aka cityhunter
#* This library is free software; you can redistribute it and/or modify
#* it under the terms of the LGPL v2.1 or latter at your option
#* http://www.gnu.org/copyleft/lesser.html
#************************************************************************/
include ${confiserie}/Makefiles/Makefile.messages

distclean : clean 
clean : clean_c_rule
clean_c_rule:
	rm -f GENERATED
	rm -f *.o

define cc_o_macro
	${CCMESG} ${MSGSUBDIR}$<
	-rm -rf $@
	mkdir -p $(dir $@)
	${CC} -c ${CCFLAGS} ${CPPFLAGS} -o $@ $<
endef

	
#automatic compilation : generate .o from .c
#this is a 'beautifull' rules : it display strings like [ CC ] lib/toto.c
%.o: %.c
	$(call cc_o_macro)
	
#automatic compilation : generate .o from .c
#this is a 'beautifull' rules : it display strings like [ CC ] lib/toto.c
GENERATED/%.o: %.c
	$(call cc_o_macro)
	

