noinst_LIBRARIES += libconfiserie
libconfiserie_SOURCES =  libconfiserie.c  libconfiserie2.c

noinst_CXXPROGRAMS = testlibconfiserie
testlibconfiserie_SOURCES = testlibconfiserie.c

include ${confiserie}/C/Makefile.autoapp
include ${confiserie}/C/Makefile.beautifull_rules
include ${confiserie}/Makefiles/Makefile.autolib

